CREATE TABLE "common_grocery_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "common_grocery_items_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "requested_delivery_date" date;--> statement-breakpoint
ALTER TABLE "service_requests" ADD COLUMN "requested_delivery_date" date;
--> statement-breakpoint

-- Seed data for the "quick add" pickers on /request-service and the staff
-- concierge order builder. sort_order is one running sequence (not reset
-- per category) so a plain ORDER BY sort_order keeps every category's
-- items together in this exact intended order. Editable directly in the
-- DB — no admin UI for this list yet.
INSERT INTO "common_grocery_items" ("name", "category", "sort_order") VALUES
  ('Bananas', 'Produce', 0),
  ('Apples', 'Produce', 1),
  ('Oranges', 'Produce', 2),
  ('Potatoes', 'Produce', 3),
  ('Onions', 'Produce', 4),
  ('Tomatoes', 'Produce', 5),
  ('Lettuce', 'Produce', 6),
  ('Carrots', 'Produce', 7),
  ('Avocados', 'Produce', 8),
  ('Lemons', 'Produce', 9),

  ('Milk', 'Dairy & Eggs', 10),
  ('Eggs', 'Dairy & Eggs', 11),
  ('Butter', 'Dairy & Eggs', 12),
  ('Cheddar Cheese', 'Dairy & Eggs', 13),
  ('Greek Yogurt', 'Dairy & Eggs', 14),
  ('Sour Cream', 'Dairy & Eggs', 15),
  ('Cream Cheese', 'Dairy & Eggs', 16),
  ('Half & Half', 'Dairy & Eggs', 17),
  ('Shredded Cheese', 'Dairy & Eggs', 18),
  ('Cottage Cheese', 'Dairy & Eggs', 19),

  ('Chicken Breast', 'Meat & Seafood', 20),
  ('Ground Beef', 'Meat & Seafood', 21),
  ('Bacon', 'Meat & Seafood', 22),
  ('Pork Chops', 'Meat & Seafood', 23),
  ('Ham', 'Meat & Seafood', 24),
  ('Sausage', 'Meat & Seafood', 25),
  ('Steak', 'Meat & Seafood', 26),
  ('Shrimp', 'Meat & Seafood', 27),
  ('Salmon', 'Meat & Seafood', 28),
  ('Deli Turkey', 'Meat & Seafood', 29),

  ('Bread', 'Bakery', 30),
  ('Bagels', 'Bakery', 31),
  ('Tortillas', 'Bakery', 32),
  ('Dinner Rolls', 'Bakery', 33),
  ('English Muffins', 'Bakery', 34),
  ('Hamburger Buns', 'Bakery', 35),
  ('Muffins', 'Bakery', 36),
  ('Birthday Cake', 'Bakery', 37),
  ('Donuts', 'Bakery', 38),
  ('Pie', 'Bakery', 39),

  ('Rice', 'Pantry & Dry Goods', 40),
  ('Pasta', 'Pantry & Dry Goods', 41),
  ('Flour', 'Pantry & Dry Goods', 42),
  ('Sugar', 'Pantry & Dry Goods', 43),
  ('Cooking Oil', 'Pantry & Dry Goods', 44),
  ('Peanut Butter', 'Pantry & Dry Goods', 45),
  ('Cereal', 'Pantry & Dry Goods', 46),
  ('Canned Beans', 'Pantry & Dry Goods', 47),
  ('Canned Soup', 'Pantry & Dry Goods', 48),
  ('Coffee', 'Pantry & Dry Goods', 49),

  ('Frozen Pizza', 'Frozen Foods', 50),
  ('Ice Cream', 'Frozen Foods', 51),
  ('Frozen Vegetables', 'Frozen Foods', 52),
  ('Frozen Fruit', 'Frozen Foods', 53),
  ('Frozen Waffles', 'Frozen Foods', 54),
  ('Frozen Chicken Nuggets', 'Frozen Foods', 55),
  ('Frozen French Fries', 'Frozen Foods', 56),
  ('Frozen Burritos', 'Frozen Foods', 57),
  ('Frozen Dinners', 'Frozen Foods', 58),
  ('Bagged Ice', 'Frozen Foods', 59),

  ('Bottled Water', 'Beverages', 60),
  ('Orange Juice', 'Beverages', 61),
  ('Soda', 'Beverages', 62),
  ('Coffee Creamer', 'Beverages', 63),
  ('Sports Drinks', 'Beverages', 64),
  ('Tea', 'Beverages', 65),
  ('Sparkling Water', 'Beverages', 66),
  ('Beer', 'Beverages', 67),
  ('Wine', 'Beverages', 68),
  ('Energy Drinks', 'Beverages', 69),

  ('Paper Towels', 'Household & Cleaning', 70),
  ('Toilet Paper', 'Household & Cleaning', 71),
  ('Dish Soap', 'Household & Cleaning', 72),
  ('Laundry Detergent', 'Household & Cleaning', 73),
  ('Trash Bags', 'Household & Cleaning', 74),
  ('All-Purpose Cleaner', 'Household & Cleaning', 75),
  ('Sponges', 'Household & Cleaning', 76),
  ('Aluminum Foil', 'Household & Cleaning', 77),
  ('Plastic Wrap', 'Household & Cleaning', 78),
  ('Bleach', 'Household & Cleaning', 79),

  ('Toothpaste', 'Personal Care & Health', 80),
  ('Shampoo', 'Personal Care & Health', 81),
  ('Deodorant', 'Personal Care & Health', 82),
  ('Bar Soap', 'Personal Care & Health', 83),
  ('Hand Sanitizer', 'Personal Care & Health', 84),
  ('Pain Reliever', 'Personal Care & Health', 85),
  ('Multivitamins', 'Personal Care & Health', 86),
  ('Band-Aids', 'Personal Care & Health', 87),
  ('Razors', 'Personal Care & Health', 88),
  ('Sunscreen', 'Personal Care & Health', 89),

  ('Dog Food', 'Pet & Ranch Supplies', 90),
  ('Cat Food', 'Pet & Ranch Supplies', 91),
  ('Livestock Feed', 'Pet & Ranch Supplies', 92),
  ('Hay', 'Pet & Ranch Supplies', 93),
  ('Salt Blocks', 'Pet & Ranch Supplies', 94),
  ('Fencing Wire', 'Pet & Ranch Supplies', 95),
  ('Work Gloves', 'Pet & Ranch Supplies', 96),
  ('Baling Twine', 'Pet & Ranch Supplies', 97),
  ('Bird Seed', 'Pet & Ranch Supplies', 98),
  ('Cat Litter', 'Pet & Ranch Supplies', 99),

  ('Diapers', 'Baby & Kids', 100),
  ('Baby Wipes', 'Baby & Kids', 101),
  ('Baby Formula', 'Baby & Kids', 102),
  ('Baby Food', 'Baby & Kids', 103),
  ('Sippy Cups', 'Baby & Kids', 104),
  ('Kids Snacks', 'Baby & Kids', 105),
  ('Baby Shampoo', 'Baby & Kids', 106),
  ('Diaper Rash Cream', 'Baby & Kids', 107),
  ('Pacifiers', 'Baby & Kids', 108),
  ('Kids Juice Boxes', 'Baby & Kids', 109)
ON CONFLICT ("name") DO NOTHING;